-- Combined Supabase schema for Harmonix Player
-- Paste the contents of this file into Supabase SQL editor and run.
-- This creates all user-data tables used by the app (favorites, flagged, queue, theme, volume, repeat, lastsong, favparts, user_profiles).
-- Run once. Tables use IF NOT EXISTS where practical to be idempotent.

-- favorites table
CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  song_id TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_song_id ON favorites(song_id);

-- flagged table
CREATE TABLE IF NOT EXISTS flagged (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  song_id TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS flagged_user_id_idx ON flagged(user_id);
CREATE INDEX IF NOT EXISTS flagged_song_id_idx ON flagged(song_id);

-- queue table
CREATE TABLE IF NOT EXISTS queue (
  user_id UUID PRIMARY KEY,
  queue JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- theme table
CREATE TABLE IF NOT EXISTS theme (
  user_id UUID PRIMARY KEY,
  theme TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- volume table
CREATE TABLE IF NOT EXISTS volume (
  user_id UUID PRIMARY KEY,
  volume FLOAT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- repeat table
CREATE TABLE IF NOT EXISTS repeat (
  user_id UUID PRIMARY KEY,
  repeat BOOLEAN NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- lastsong table
CREATE TABLE IF NOT EXISTS lastsong (
  user_id UUID PRIMARY KEY,
  songIndex INT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- favparts table
CREATE TABLE IF NOT EXISTS favparts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  songIndex INT NOT NULL,
  start FLOAT NOT NULL,
  end FLOAT NOT NULL,
  name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS favparts_user_id_idx ON favparts(user_id);
CREATE INDEX IF NOT EXISTS favparts_song_idx ON favparts(songIndex);

-- user_profiles table
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id UUID PRIMARY KEY,
  country_code TEXT,
  country_name TEXT,
  metadata JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS user_profiles_country_idx ON user_profiles(country_code);

-- Optional: add a comment to indicate end of file
-- End of schema
